"""added settings table

Revision ID: 040f40ab6f1e
Revises: 0ec6b38eac92
Create Date: 2026-04-03 11:37:40.366488
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040f40ab6f1e'
down_revision = '0ec6b38eac92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_settings_key'))
    )
    op.alter_column('order_addresses', 'country_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_addresses', 'country_code',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_table('settings')
    # ### end Alembic commands ###
