"""add_category_customization_rules

Revision ID: 54e1b9c2a0c0
Revises: 1cf2b875deb5
Create Date: 2026-04-02 11:42:25.029855
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54e1b9c2a0c0'
down_revision = '1cf2b875deb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_customization_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=True),
    sa.Column('allowed_file_types', sa.String(length=255), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_customization_rules_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_customization_rules'))
    )
    op.create_index(op.f('ix_category_customization_rules_category_id'), 'category_customization_rules', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_customization_rules_category_id'), table_name='category_customization_rules')
    op.drop_table('category_customization_rules')
    # ### end Alembic commands ###
